### ISSUE TITLE
problem with node BefOS

### ISSUE THREAD

**Issue by tomory** [catseye/Chrysoberyl#6]
The link on http://catseye.tc/node/BefOS labeled "src/page/tutorial.txt", to http://catseye.tc/view/befos/src/page/tutorial.txt, is broken.

**Comment by cpressey** [comment]
Thanks for letting me know @tomory -- I'll try to fix it soon.  In the meantime you can see BefOS's documentation on Github here: https://github.com/catseye/BefOS

**Comment by cpressey** [comment]
Fixed, finally.  The latest released version of BefOS is 0.10, but the files on the server were stuck at 0.9 and the doc index was out of sync.  http://catseye.tc/view/befos/src/page/tutorial.txt is there now.
